### ISSUE TITLE
Cannot view pictures on IOS13

### ISSUE THREAD

**Issue by psl2806** [gregstoll/gallery2#10]

**Comment by psl2806** [comment]
After the upgrade to IOS 13. I can browse through the folder structure, see the thumbnails but canmot tap and view the picture full screen

**Comment by gregstoll** [comment]
Sorry about this. I don't have an iOS device - anyone willing to help out?

**Comment by Filou83** [comment]
I tried it on iOS 12, iOS 14 and iOS 15 without issues (no device with outdated iOS 13 available). I think the bug can be closed.

**Comment by gregstoll** [comment]
Awesome - thanks for trying it out @Filou83!
