### ISSUE TITLE
Module Dynamic Albums 

### ISSUE THREAD

**Issue by Turk1701** [gregstoll/gallery2#100]
Updates works. But both Popular and Random results in a blank white page with no page source. Here is the bit in the servers error.log:
`[Sun Dec 04 19:06:47.659730 2022] [fcgid:warn] [pid 207245:tid 3888047167232] [client 68.187.77.160:65201] mod_fcgid: stderr: PHP Fatal error:  Declaration of RandomAlbumView::getChildIds($userId) must be compatible with UpdatesAlbumView::getChildIds($userId, $param = 'date', $orderBy = 'creationTi...', $orderDirection = ORDER_DESCENDING, $table = 'GalleryEnt...', $id = 'id') in /home/turk1701/hotelblues.com/gallery2/modules/dynamicalbum/RandomAlbum.inc on line 48, referer: https://www.hotelblues.com/gallery2/admin/?g2_subView=dynamicalbum.DynamicAlbumSiteAdmin
[Sun Dec 04 19:08:23.299242 2022] [fcgid:warn] [pid 207245:tid 3889591424768] [client 68.187.77.160:49907] mod_fcgid: stderr: PHP Fatal error:  Declaration of PopularAlbumView::getChildIds($userId) must be compatible with UpdatesAlbumView::getChildIds($userId, $param = 'date', $orderBy = 'creationTi...', $orderDirection = ORDER_DESCENDING, $table = 'GalleryEnt...', $id = 'id') in /home/turk1701/hotelblues.com/gallery2/modules/dynamicalbum/PopularAlbum.inc on line 48, referer: https://www.hotelblues.com/gallery2/main.php`

**Comment by gregstoll** [comment]
OK, I think the change I put in should fix this. There was a bit of weirdness around this code, though, so let me know if you see any problems!

**Comment by Turk1701** [comment]
That did it. I think that is all of my bugs. Thanks again for the hard work you do on this.

**Comment by gregstoll** [comment]
No problem! Very nice to see there are still people using gallery :-)
