### ISSUE TITLE
Webdav plugin cannot be activated

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#129]
The attached patch fixes that.

There are most likely quite a few functions in the webdav module that must be made static in order to make it work properly but I haven't verified that. 

[webdav.txt](https://github.com/gregstoll/gallery2/files/10328891/webdav.txt)

**Comment by gregstoll** [comment]
Thanks, things are a bit busy now, I'll try to look at this soon.
