### ISSUE TITLE
bug in PasswordHelper.class introduced in 4d7f661d0f9aaef6a4a9bab464b961ec413a0bc7

### ISSUE THREAD

**Issue by matthewluckie** [gregstoll/gallery2#13]
In commit 4d7f661d0f9aaef6a4a9bab464b961ec413a0bc7, you added static to the setPassword and removePassword methods in modules/password/classes/PasswordHelper.class.  This causes the following php 7.2 errors when creating a sub-album:

[Sat Apr 18 12:06:00.805614 2020] [php7:error] [pid 57042] [client 192.168.2.29:63880] PHP Fatal error:  Cannot make non static method PasswordInterface_1_0::setPassword() static in class PasswordHelper in /usr/local/www/gallery2/modules/password/classes/PasswordHelper.class on line 30, referer: redacted

[Sat Apr 18 12:15:26.018082 2020] [php7:error] [pid 55723] [client 192.168.2.29:63956] PHP Fatal error:  Cannot make non static method PasswordInterface_1_0::removePassword() static in class PasswordHelper in /usr/local/www/gallery2/modules/password/classes/PasswordHelper.class on line 30, referer: redacted

removing the static keyword from these two methods allows the albums to be created.  my suggestion is to remove the static keyword from these methods.

**Comment by gregstoll** [comment]
Hi -

Yes, I believe this was a problem, but I fixed it in commit 8bb4429c90ca06790f267fdbaf82155a21192100.  Try pulling from that and let me know if that fixes the issue.

Thanks!

**Comment by matthewluckie** [comment]
sorry for the noise
