### ISSUE TITLE
adding a .MOV to an album via the "from web browser" tab causes a thumbnail warning

### ISSUE THREAD

**Issue by matthewluckie** [gregstoll/gallery2#14]
The warnings look like:

[Sat Apr 18 19:42:25.412824 2020] [php7:warn] [pid 58189] [client 192.168.2.29:50516] PHP Warning:  Declaration of ThumbnailImage::create($inputFileName, $mimeType, $targetName = NULL, $parentId = NULL) should be compatible with GalleryFileSystemEntity::create($parentId = false, $pathComponent = false, $isDirectory = false) in /usr/local/www/gallery2/modules/thumbnail/classes/ThumbnailImage.class on line 561, referer: redacted
[Sat Apr 18 19:42:25.412999 2020] [php7:warn] [pid 58189] [client 192.168.2.29:50516] PHP Warning:  Declaration of ThumbnailImage::save($postEvent = true) should be compatible with GalleryEntity::save($postEvent = true, $setAclId = NULL) in /usr/local/www/gallery2/modules/thumbnail/classes/ThumbnailImage.class on line 561, referer: redacted

I found that this was fixed in commit f2a5f178 of https://github.com/hlh-restart/gallery2-1

Matthew

**Comment by gregstoll** [comment]
Thanks for the report!  I'll try to look into this this week.
