### ISSUE TITLE
Lots of PHP Notices in webserver errorlog

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#142]
The adodb/smarty upgrade creates lots of "PHP Notice:  Only variables should be assigned by reference in /usr/local/www/gallery2/modules/core/classes/GalleryStorage.class on line 1541" in the webserver errorlog. The attached patch should fix that.

[excessive-log.txt](https://github.com/gregstoll/gallery2/files/11302125/excessive-log.txt)

**Comment by gregstoll** [comment]
Sorry, I meant to make a proper PR for this but messed up and pushed [commit 9faff54](https://github.com/gregstoll/gallery2/commit/9faff54ff223ac8660e5fe003265e58dfa9b0455) directly to main. Thanks for the fix - checked my logs and they were giant!
