### ISSUE TITLE
ImageBlock plugin broken after adodb upgrade when using PostgreSQL as database

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#143]
After the adodb upgrade the ImageBlock plugin throws an SQL error when using PostgreSQL as database due to a typecast mismatch. The error message is 'ERROR:  column "g_userid" is of type integer but expression is of type text
 at character 59'. The root cause seems to be change in how adodb and/or PostgreSQL handles implicit typecasting.

I have attached a patch that solves the issue and as far as I can tell after tests, it also works when using MySQL/mariadb as database. I am not entirely happy with the patch since it might break the compatibility with other databases than pgsql/mysql/mariadb but without it the ImageBlock plugin does not work at all with PostgreSQL.

If the patch is accepted it also solves issue 123.

[imageblock.txt](https://github.com/gregstoll/gallery2/files/11510989/imageblock.txt)

**Comment by gregstoll** [comment]
Thanks a bunch! Can confirm this works fine with MySQL/mariadb, and it seems like this follows general SQL usage.

I messed up the branching again but this has been applied in commit 0dfe2be. Closing.
