### ISSUE TITLE
adding a .mov to an album via the "From Local Server" tab causes a warning

### ISSUE THREAD

**Issue by matthewluckie** [gregstoll/gallery2#15]
The warning looks like this:

[Sat Apr 18 20:18:26.571998 2020] [php7:warn] [pid 55726] [client 192.168.2.29:51006] PHP Warning:  Declaration of GalleryUnknownItem::create($parentId, $inputFileName, $mimeType, $targetName = NULL, $symlink = false) should be compatible with GalleryDataItem::create($parentId = false, $inputFileName = false, $mimeType = false, $targetName = NULL, $symlink = false) in /usr/local/www/gallery2/modules/core/classes/GalleryUnknownItem.class on line 41, referer: redacted.

I have attached a patch, that follows the style of other patches that you have made that inherit from GalleryDataItem, which stops the warning.

[patch-GalleryUnknownItem.txt](https://github.com/gregstoll/gallery2/files/4496331/patch-GalleryUnknownItem.txt)

**Comment by gregstoll** [comment]
Thanks for the patch!  I'll try to look into this this week.

**Comment by gregstoll** [comment]
Pulled in this change in the linked commit. Thanks again!
