### ISSUE TITLE
Remote upload problem

### ISSUE THREAD

**Issue by sysprg1** [gregstoll/gallery2#164]
Hi, first of all: Thank you, great work.!
I noticed that users can't upload photos via remote protocol:
PHP Fatal error:  Uncaught Error: Non-static method GalleryRemoteConstants::getStatusCodes() cannot be called statically in ***/modules/remote/GalleryRemote.inc:75\nStack trace:\n#0 ***/main.php(250): GalleryRemoteController->handleRequest()\n#1 ***/main.php(104): _GalleryMain()\n#2 ***/main.php(88): GalleryMain()\n#3 {main}\n  thrown in ***/modules/remote/GalleryRemote.inc on line 75

**Comment by gregstoll** [comment]
Oh, thanks for the report! I don't use the remote protocol so I haven't had a chance to test it, so there may be other lurking issues; please feel free to file them! (this one should be easy to fix, though)

**Comment by sysprg1** [comment]
Perfect!
