### ISSUE TITLE
Plugin enable/disable broken (multisite)

### ISSUE THREAD

**Issue by starlilyth** [gregstoll/gallery2#18]
I have a Gallery2 Multisite install, and used this fork to upgrade to PHP7.

I was unable to enable or disable plugins in a site until I changed line 362 in gallery2/modules/core/PluginCallback.inc

I was getting this error from debug log: 
"PHP Fatal error:  Uncaught Error: Using $this when not in object context in <path/to/>gallery2/modules/core/PluginCallback.inc:362"

I changed line 362 from this:

$this->getPluginState($type, $plugin, $status);

to this:

PluginCallbackView::getPluginState($type, $plugin, $status);

Now I can enable and disable plugins!

**Comment by gregstoll** [comment]
Thanks a bunch for the fix!
