### ISSUE TITLE
installation not working under php 5.6

### ISSUE THREAD

**Issue by crisc2000** [gregstoll/gallery2#2]
I have tried to install this on PHP 5.6 using the normal installation method, by accessing www.site.com/gallery2/install/
It do not work, it gets stuck when trying to authenticate with login.txt
> "Error: your login.txt key does not match correctly. Please download a new authentication string from below and try again. "

No mater how many login.txt with the code you will create it will give the same error.
Original 2.3.2 version pass over login.txt step, but it give (fatal) error later on another step.

**Comment by gregstoll** [comment]
Hi! Sorry for the trouble.

I created this for to work with PHP 7, which may have some incompatibilities with PHP 5.6.  Have you tried the standard gallery install from [galleryproject.org](http://galleryproject.org)?

Unfortunately my life is pretty busy right now so I'm probably not going to have much time to help you try to debug the issue.  Sorry!
