### ISSUE TITLE
Major problems with PHP 8 on Fedora 35

### ISSUE THREAD

**Issue by mhwarfield** [gregstoll/gallery2#23]
Upgraded to Fedora 35 with PHP 8.  Gallery2 would not run.  Downloaded latest package.  No joy.  Set error logging on.

Errors like:
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /usr/share/gallery2/modules/core/classes/GalleryUrlGenerator.class on line 153

Cleaned those with {0} -> [0] in several locations

Parse errors on 
and

Fatal error: Uncaught Error: Non-static method GalleryUtilities::isSafeHttpHeader() cannot be called statically in /usr/share/gallery2/modules/core/classes/GalleryPhpVm.class:138 Stack trace: #0 /usr/share/gallery2/index.php(48): GalleryPhpVm->header() #1 {main} thrown in /usr/share/gallery2/modules/core/classes/GalleryPhpVm.class on line 138

**Comment by gregstoll** [comment]
Ugh, that's unfortunate. I can try to get this set up at some point and fix the issues but with the holidays approaching I don't have a lot of spare time. I'd be happy to accept PRs though!

**Comment by Filou83** [comment]
Would be really nice if you could try to fix the issues with php 8 - I still love gallery2 and your work is highly appreciated.
Thank you and have a happy christmas time.

**Comment by gregstoll** [comment]
HI @mhwarfield - I think this repo has changes that will fix these issues - for example this version of GalleryUrlGenerator.class [does use square brackets on line 153](https://github.com/gregstoll/gallery2/blob/master/modules/core/classes/GalleryUrlGenerator.class#L153). However, this repo is not the officially distributed package.

What I did was to clone or download a copy of this repo and then copy the files to `/usr/share/gallery2` over the officially installed package. After you've done that, try restarting apache and seeing if the errors go away. Thanks!

**Comment by gregstoll** [comment]
As I'm pretty sure this problem is fixed, I'm going to close this issue. But feel free to file any other issues y'all see with PHP 8!

**Comment by gregstoll** [comment]
OK, I'm not sure what I was trying, but there are definitely more problems with PHP 8. I have stuff generally working in the [php8 branch](https://github.com/gregstoll/gallery2/tree/php8) - hoping to merge that into main soon. Reopening until then.
