### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by gregstoll** [gregstoll/gallery2#32]
reported [here](https://github.com/gregstoll/gallery2/issues/29#issuecomment-1271098242):

Fatal error: Uncaught Error: Non-static method CoreModuleExtras::upgrade() cannot be called statically in /home/gallery2/modules/core/module.inc:486 Stack trace: #0 /home/gallery2/modules/core/classes/GalleryModule.class(175): CoreModule->upgrade() https://github.com/gregstoll/gallery2/pull/1 /home/gallery2/install/steps/InstallCoreModuleStep.class(143): GalleryModule->installOrUpgrade() https://github.com/gregstoll/gallery2/issues/2 /home/gallery2/install/index.php(158): InstallCoreModuleStep->processRequest() https://github.com/gregstoll/gallery2/pull/3 {main} thrown in /home/gallery2/modules/core/module.inc on line 486

**Comment by gregstoll** [comment]
@hjschiller - want to try again? :-)

**Comment by hjschiller** [comment]
progress!

Fatal error: Uncaught Error: Non-static method GalleryPluginHelper_medium::_addParameter() cannot be called statically in /home/gallery2/modules/core/classes/helpers/GalleryPluginHelper_medium.class:308 Stack trace: #0 /home/gallery2/modules/core/classes/GalleryCoreApi.class(482): GalleryPluginHelper_medium::setParameter() #1 /home/gallery2/modules/core/classes/GalleryPlugin.class(526): GalleryCoreApi::setPluginParameter() #2 /home/gallery2/modules/core/CoreModuleExtras.inc(217): GalleryPlugin->setParameter() #3 /home/gallery2/modules/core/module.inc(486): CoreModuleExtras::upgrade() #4 /home/gallery2/modules/core/classes/GalleryModule.class(175): CoreModule->upgrade() #5 /home/gallery2/install/steps/InstallCoreModuleStep.class(143): GalleryModule->installOrUpgrade() #6 /home/gallery2/install/index.php(158): InstallCoreModuleStep->processRequest() #7 {main} thrown in /home/gallery2/modules/core/classes/helpers/GalleryPluginHelper_medium.class on line 308
