### ISSUE TITLE
core plugins now broken during install

### ISSUE THREAD

**Issue by hjschiller** [gregstoll/gallery2#40]
Fatal error: Uncaught Error: Non-static method GalleryPluginHelper_medium::_addParameter() cannot be called statically in /home/gallery2/modules/core/classes/helpers/GalleryPluginHelper_medium.class:308 Stack trace: #0 /home/gallery2/modules/core/classes/GalleryCoreApi.class(482): GalleryPluginHelper_medium::setParameter() #1 /home/gallery2/modules/core/classes/GalleryPlugin.class(526): GalleryCoreApi::setPluginParameter() #2 /home/gallery2/modules/core/CoreModuleExtras.inc(217): GalleryPlugin->setParameter() #3 /home/gallery2/modules/core/module.inc(486): CoreModuleExtras::upgrade() #4 /home/gallery2/modules/core/classes/GalleryModule.class(175): CoreModule->upgrade() #5 /home/gallery2/install/steps/InstallCoreModuleStep.class(143): GalleryModule->installOrUpgrade() #6 /home/gallery2/install/index.php(158): InstallCoreModuleStep->processRequest() #7 {main} thrown in /home/gallery2/modules/core/classes/helpers/GalleryPluginHelper_medium.class on line 308

**Comment by hjschiller** [comment]
ok, too many dependencies for me to sort this one out...
@gregstoll , can you look at this one when you have a chance?

current error is:

Fatal error: Uncaught Error: Non-static method GalleryPluginHelper_medium::_addParameter() cannot be called statically in /home/gallery2/modules/core/classes/helpers/GalleryPluginHelper_medium.class:308 Stack trace: #0 /home/gallery2/modules/core/classes/GalleryCoreApi.class(482): GalleryPluginHelper_medium::setParameter() #1 /home/gallery2/modules/core/classes/GalleryPlugin.class(526): GalleryCoreApi::setPluginParameter() #2 /home/gallery2/modules/core/CoreModuleExtras.inc(217): GalleryPlugin->setParameter() #3 /home/gallery2/modules/core/module.inc(486): CoreModuleExtras::upgrade() #4 /home/gallery2/modules/core/classes/GalleryModule.class(175): CoreModule->upgrade() #5 /home/gallery2/install/steps/InstallCoreModuleStep.class(143): GalleryModule->installOrUpgrade() #6 /home/gallery2/install/index.php(158): InstallCoreModuleStep->processRequest() #7 {main} thrown in /home/gallery2/modules/core/classes/helpers/GalleryPluginHelper_medium.class on line 308

**Comment by gregstoll** [comment]
Weird, I submitted a fix for this but it looks like you did the same thing. Are you still seeing that error?

**Comment by hjschiller** [comment]
Yes, I am seeing issue 40 as broken. I didn’t see this issue at first, and
think it is a result of one of the plug-in fixes.

 I think issue #34 is fixed, but can’t confirm because I’m seeing issue 40.

___Jason

**Comment by gregstoll** [comment]
Hm, that's very weird. Are you sure it's the exact same error message? Really seems like our fix should have fixed this.

It does look like [this commit](https://github.com/hjschiller/gallery2/commit/7c5a83e12ea03b4accb973279102ddb186769247) is suspicious - I think I made that a static function in a separate change.

I'm not sure what your workflow is, but if you're using your own repo it looks like you're missing some of the latest changes here. If you'd rather fix stuff in your repo and make pull requests for them, that's totally fine too!

**Comment by hjschiller** [comment]
I think so.  Give me an hour and I’ll do a clean install and post a new
error with the message.

__Jason

**Comment by hjschiller** [comment]
Strange, it is fine now. I am certain I saw this get rebroken.

I’m pretty sure all the in flight changes were submitted.

Now the install is good up to some of the plugins.

I can work on the plugins this weekend.

___Jason

**Comment by gregstoll** [comment]
Awesome, glad to hear it!
