### ISSUE TITLE
Failure to identify gd and jpegtran versions

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#55]
The gd plugin is unable to identify 2.x versions newer than 2.1. Also the jpegtran plugin fails to identify jpegtran from jpeg-turbo-2.x as a valid jpegtran binary. The patch below fixes both issues.

[gd-jpegtran.txt](https://github.com/gregstoll/gallery2/files/9789416/gd-jpegtran.txt)

**Comment by gregstoll** [comment]
Thanks - much appreciated!
