### ISSUE TITLE
add image from local server warning

### ISSUE THREAD

**Issue by hjschiller** [gregstoll/gallery2#60]
[Sat Oct 15 04:17:43.197988 2022] [php:warn] [pid 399485] [client 192.168.1.63:56118] PHP Warning:  Trying to access array offset on value of type null in /home/gallery2/modules/core/classes/helpers/GalleryToolkitHelper_simple.class on line 104, referer: https://www.schiller.net/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemAdd&g2_addPlugin=ItemAddFromServer&g2_form%5BlocalServerPath%5D=/home/photos2&g2_itemId=7&g2_form%5Baction%5D%5BfindFilesFromLocalServer%5D=1&g2_form%5BformName%5D=ItemAddFromServer

**Comment by hjschiller** [comment]
image loads fine.

**Comment by gregstoll** [comment]
I think this might be fixed with [commit f2583cf5](https://github.com/gregstoll/gallery2/commit/f2583cf5139e3b124e68166293544401bafc891e) - can you try this again?

**Comment by hjschiller** [comment]
Greg,

I don’t know about this fix.

I did a git fetch, logged in as admin, clicked on theme and clicked the
save theme update, then loaded the gallery. Still didn’t render.

(See logs below)

I did a fresh install and it failed to fully install the core modules.
There were no logs. The error said

X Core module only partially installed.
X Error installing Gallery core

It references an install log which does not exist.
And nothing in the apachie2 error logs.

I can try again from my laptop a bit later.

___Jason

[Thu Oct 27 11:05:10.667119 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:53571] PHP Warning:  Undefined
property: Services_JSON::$use in /home/gallery2/lib/JSON/JSON.php on line
617, referer:
https://www.schiller.net/gallery2/main.php?g2_view=core.SiteAdmin&g2_subView=core.AdminThemes
[Thu Oct 27 11:05:10.667207 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:53571] PHP Warning:  Undefined
property: Services_JSON::$use in /home/gallery2/lib/JSON/JSON.php on line
617, referer:
https://www.schiller.net/gallery2/main.php?g2_view=core.SiteAdmin&g2_subView=core.AdminThemes
[Thu Oct 27 11:05:10.667277 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:53571] PHP Warning:  Undefined
property: Services_JSON::$use in /home/gallery2/lib/JSON/JSON.php on line
617, referer:
https://www.schiller.net/gallery2/main.php?g2_view=core.SiteAdmin&g2_subView=core.AdminThemes
[Thu Oct 27 11:05:10.667363 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:53571] PHP Warning:  Undefined
property: Services_JSON::$use in /home/gallery2/lib/JSON/JSON.php on line
617, referer:
https://www.schiller.net/gallery2/main.php?g2_view=core.SiteAdmin&g2_subView=core.AdminThemes
[Thu Oct 27 11:05:16.349119 2022] [php:error] [pid 3372136] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:53573] PHP Fatal error:  Uncaught
Error: Cannot use object of type stdClass as array in
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class:974\nStack
trace:\n#0
/home/photos/smarty/templates_c/%%201819508/matrix/%%B4^B49^B49848CB%%sidebar.tpl.php(7):
GalleryTemplateAdapter->block()\n#1
/home/gallery2/lib/smarty/Smarty.class.php(1868):
include('/home/photos/sm...')\n#2
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class(907):
Smarty->_smarty_include()\n#3
/home/photos/smarty/templates_c/%%201819508/matrix/%%42^42C^42CE7724%%album.tpl.php(9):
GalleryTemplateAdapter->theme()\n#4
/home/gallery2/lib/smarty/Smarty.class.php(1868):
include('/home/photos/sm...')\n#5
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class(907):
Smarty->_smarty_include()\n#6
/home/photos/smarty/templates_c/%%201819508/matrix/%%3A^3A8^3A818B59%%theme.tpl.php(52):
GalleryTemplateAdapter->theme()\n#7
/home/gallery2/lib/smarty/Smarty.class.php(1262):
include('/home/photos/sm...')\n#8
/home/gallery2/modules/core/classes/GallerySmarty.class(58):
Smarty->fetch()\n#9
/home/gallery2/modules/core/classes/GalleryTemplate.class(219):
GallerySmarty->fetch()\n#10 /home/gallery2/main.php(521):
GalleryTemplate->fetch()\n#11 /home/gallery2/main.php(104):
_GalleryMain()\n#12 /home/gallery2/main.php(88): GalleryMain()\n#13
{main}\n  thrown in
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class on line
974, referer:
https://www.schiller.net/gallery2/main.php?g2_view=core.SiteAdmin&g2_subView=core.AdminThemes&g2_themeId=matrix
[Thu Oct 27 11:05:23.833823 2022] [php:error] [pid 3372135] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:53574] PHP Fatal error:  Uncaught
Error: Cannot use object of type stdClass as array in
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class:974\nStack
trace:\n#0
/home/photos/smarty/templates_c/%%201819508/matrix/%%B4^B49^B49848CB%%sidebar.tpl.php(7):
GalleryTemplateAdapter->block()\n#1
/home/gallery2/lib/smarty/Smarty.class.php(1868):
include('/home/photos/sm...')\n#2
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class(907):
Smarty->_smarty_include()\n#3
/home/photos/smarty/templates_c/%%201819508/matrix/%%42^42C^42CE7724%%album.tpl.php(9):
GalleryTemplateAdapter->theme()\n#4
/home/gallery2/lib/smarty/Smarty.class.php(1868):
include('/home/photos/sm...')\n#5
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class(907):
Smarty->_smarty_include()\n#6
/home/photos/smarty/templates_c/%%201819508/matrix/%%3A^3A8^3A818B59%%theme.tpl.php(52):
GalleryTemplateAdapter->theme()\n#7
/home/gallery2/lib/smarty/Smarty.class.php(1262):
include('/home/photos/sm...')\n#8
/home/gallery2/modules/core/classes/GallerySmarty.class(58):
Smarty->fetch()\n#9
/home/gallery2/modules/core/classes/GalleryTemplate.class(219):
GallerySmarty->fetch()\n#10 /home/gallery2/main.php(521):
GalleryTemplate->fetch()\n#11 /home/gallery2/main.php(104):
_GalleryMain()\n#12 /home/gallery2/main.php(88): GalleryMain()\n#13
{main}\n  thrown in
/home/gallery2/modules/core/classes/GalleryTemplateAdapter.class on line
974, referer:
https://www.schiller.net/gallery2/main.php?g2_view=core.SiteAdmin&g2_subView=core.AdminThemes&g2_themeId=matrix

**Comment by gregstoll** [comment]
Hmm, that's not good :-/

Those PHP errors are confusing, though; I would have expected them to go away with [commit 5cdaf059](https://github.com/gregstoll/gallery2/commit/5cdaf059ee01697e6495f81fdf4fc1545771dade). Can you make sure you have the latest changes? You can look at `lib/JSON/JSON.php` line 133 - it should have `__construct` and not `Services_JSON`.

**Comment by hjschiller** [comment]
Apologies.

cat lib/JSON/JSON.php | sed -n '133p'
    function Services_JSON($use = 0)

I though a git fetch would bring me to head….

Update shortly

___Jason

**Comment by hjschiller** [comment]
Success!

I did see a few warnings during the core module install, but let’s close
out this issue.


___Jason

The core install warnings were:

[Thu Oct 27 19:21:16.333732 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:55200] PHP Warning:  Trying to
access array offset on value of type bool in
/home/gallery2/modules/core/classes/GalleryGroup.class on line 98, referer:
https://www.schiller.net/gallery2/install/index.php?step=7
[Thu Oct 27 19:21:16.490911 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:55200] PHP Warning:  Trying to
access array offset on value of type bool in
/home/gallery2/modules/core/classes/GalleryGroup.class on line 98, referer:
https://www.schiller.net/gallery2/install/index.php?step=7
[Thu Oct 27 19:21:16.699227 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:55200] PHP Warning:  Trying to
access array offset on value of type bool in
/home/gallery2/modules/core/classes/GalleryGroup.class on line 98, referer:
https://www.schiller.net/gallery2/install/index.php?step=7
[Thu Oct 27 19:21:16.925380 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:55200] PHP Warning:  Trying to
access array offset on value of type bool in
/home/gallery2/modules/core/classes/GalleryUser.class on line 148, referer:
https://www.schiller.net/gallery2/install/index.php?step=7
[Thu Oct 27 19:21:17.480344 2022] [php:warn] [pid 3732388] [client
2607:fb90:25d5:439f:e082:8751:8ead:ba7d:55200] PHP Warning:  Trying to
access array offset on value of type bool in
/home/gallery2/modules/core/classes/GalleryUser.class on line 148, referer:
https://www.schiller.net/gallery2/install/index.php?step=7

**Comment by gregstoll** [comment]
Awesome! Yeah, git fetch just updates your local database, you have to do git pull (or a myriad of other options) to update the files on disk.
