### ISSUE TITLE
Commit 8df3f19e46f97a89a9e1cdc0b59549bb7eaee793 breaks changing resize sizes in Edit Albums

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#64]
The commit 8df3f19e46f97a89a9e1cdc0b59549bb7eaee793 to lines 715-717/718 breaks the ability to change the Target Size for Resized Images on the Album Tab in Edit Albums. With the commit applied an additional row with blank height and width is inserted into the database. Backing out the change on lines 715-717/718 fixes the issue in Edit Album.

**Comment by gregstoll** [comment]
Thanks! I hope to look at this soon.

**Comment by gregstoll** [comment]
OK, I think [commit 81a15336](https://github.com/gregstoll/gallery2/commit/81a15336d4e94f385bcf73531de60f2eb1921718) will fix this issue. I wasn't aware that coercing a string to bool will return `false` if the string is "0". Let me know if this fixes it for you!

**Comment by kaeni1Ohkohd** [comment]
Yes, this fixes the issue. Thanks
