### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by miceno** [gregstoll/gallery2#65]
Hi!

I am a volunteer on an organization that is using Gallery2 for a heritage website in Spain (https://fotos.arxiuhistoricpoblenou.cat)

I have just found this repository and I would like to know more details, since I am planning to migrate our setup to PHP8.

I have just move around the repository and here are my comments:
* translations, I have not found translations. Do you plan to include them?
* modules, I have found all the modules in the same repo as the main core. Do you plan to support all of the community plugins?
* community. Is there any plan to build a community around this code? I mean, a "team" to maintain it.

I think my organization is not the only one using Gallery2 and facing the EOL of PHP7.

**Comment by gregstoll** [comment]
Hi, thanks for getting in touch!

So the current status is that a good chunk of Gallery functionality works in PHP8. I've tested the stuff I use on my personal site, and it mostly works. I know others have run into other problems, and we fix those as we are able.

I'm happy to include translations if someone can point me at them; I haven't looked into how they work.

Just to set expectations, I'm only able to work on this in my free time, which comes and goes with family life, etc. It would be great if more people wanted to contribute (and some have already!), but I don't know if that's going to happen. I'm also not very experienced at PHP, which makes some issues take a while to fix.

I hope this helps answer your questions!
