### ISSUE TITLE
PHP Fatal error in lib/adodb/drivers/adodb-postgres64.inc.php on line 581 after upgrade to php 8.0

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#66]
Due to a function declaration mismatch Gallery2 fails with the error message "PHP Fatal error:  Declaration of & ADODB_postgres64::MetaIndexes($table, $primary = false) must be compatible with & ADOConnection::MetaIndexes($table, $primary = false, $owner = false) in /usr/local/www/gallery2/lib/adodb/drivers/adodb-postgres64.inc.php on line 581". The attached patch fixes the issue.
[adodb-fix.txt](https://github.com/gregstoll/gallery2/files/9845031/adodb-fix.txt)

**Comment by gregstoll** [comment]
Applied this in [commit ccaab5dd](https://github.com/gregstoll/gallery2/commit/ccaab5dde0fbd176b05ac702bff3422c07f82272) - thank you!
