### ISSUE TITLE
Unable to add items to album if any watermarks has been uploaded

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#68]
Trying to add items to an album when uploaded watermarks exists fails with the PHP Fatal error "PHP Fatal error:  Uncaught Error: Non-static method WatermarkHelper::fetchWatermarks() cannot be called statically in /usr/local/www/gallery2/modules/watermark/WatermarkOption.inc:72". The attached patch solves this partially, but a PHP warning, "Trying to access array offset on value of type null in /usr/local/www/gallery2/modules/core/classes/helpers/GalleryToolkitHelper_simple.class on line 104", still remains after applying the patch.

[watermark.txt](https://github.com/gregstoll/gallery2/files/9847459/watermark.txt)

**Comment by gregstoll** [comment]
I applied your fixes in [commit 75aa32f2](https://github.com/gregstoll/gallery2/commit/75aa32f2e0f45877414af9486bbc14bb4099d994) - thanks!

The other problem is interesting - it looks like stale data in your cache might cause this. Can you delete your cache and try again? (mine is in /var/lib/gallery2/g2data/cache)

**Comment by kaeni1Ohkohd** [comment]
Deleting the cache makes no difference unfortunately

**Comment by gregstoll** [comment]
Interesting, this is the same warning as in #60.

**Comment by gregstoll** [comment]
Can you turn on debugging in config.php (preferably immediate debugging) and paste the results here? I'm curious to see whether this is doing a database query or not - from the code around that line it seems like it should be.

**Comment by kaeni1Ohkohd** [comment]
The output is attached. The warning is on line 35 in the output. It looks like your guess about the database query is correct.

The debug output also show a lot of deprecated functions due to the ancient adodb. Upgrading adodb probably wouldn't hurt but that's a separate issue with it's own can of worms.

[issue-68-debug.txt](https://github.com/gregstoll/gallery2/files/9868826/issue-68-debug.txt)

**Comment by gregstoll** [comment]
OK, thanks! I think [commit f2583cf5](https://github.com/gregstoll/gallery2/commit/f2583cf5139e3b124e68166293544401bafc891e) might fix this - can you try it again?

**Comment by kaeni1Ohkohd** [comment]
That commit seems to solve the issue. The PHP warning is gone and I can't see any unwanted side effects. Thanks :-)

**Comment by gregstoll** [comment]
Great! No problem :-)
