### ISSUE TITLE
Access to Gallery2 without browser

### ISSUE THREAD

**Issue by witchi** [gregstoll/gallery2#7]
I try to access a Gallery2 instance to get the image block from another application. But it only works, if I have logged into the Gallery within the same browser.

Gallery2 uses a cookie called GALLERYSID, which is set on every GET request by the browser. There is also a variant with an URL parameter g2_GALLERYSID, but both seems not to work in my case. My application sends a POST request to the UserLogin form of G2 and gets the returned cookie. Then I send GET requests to the ImageBlock form with the cookie. I get the HTML page with the current random image only once, the second request returns an empty page and a "Set-Cookie" header with an invalidated cookie. So it seems, that G2 needs more information within my requests to leave the cookie in a valid state and to create a image response.

Do you know, what G2 needs in this case?
Thanks a lot
André

**Comment by gregstoll** [comment]
Hi, thanks for posting!  I don't know but I will try to do some research and get back to you.

**Comment by witchi** [comment]
I have found a solution (in Ruby):

```ruby
require 'cgi'
require 'httpclient'
require 'nokogiri'

def urlencode(str)
     if str == nil
         return ""
     end
     CGI::escape(str)
end

def isSuccess(status)
    return (status / 100) == 2
end

def isRedirect(status)
    return (status / 100) == 3
end

httpClient = HTTPClient.new()

formData = Array.new()
formData << ("g2_controller=" + urlencode("core.UserLogin"))
formData << ("g2_form[action][login]=" + urlencode("Login"))
formData << ("g2_form[formName]=" + urlencode("UserLogin"))
formData << ("g2_form[username]=" + urlencode("user"))
formData << ("g2_form[password]=" + urlencode("secret"))
formData << ("g2_formUrl=" + urlencode("/main.php?g2_view=core.UserAdmin&g2_subView=core.UserLogin"))

header = Hash.new()
header["Content-Type"] = "application/x-www-form-urlencoded"

response = httpClient.post("https://gallery.myserver.domain/main.php", :body => formData.join("&"), :header => header)
if not (isSuccess(response.status) || isRedirect(response.status))
    raise "Cannot get Gallery2 session id, login failed (HTTP status: " + response.status.to_s() + ")."
end

response.cookies.each do |cookie|
    if cookie.name == "GALLERYSID" && cookie.value != "" && cookie.value != nil
        # store cookie.expires
        break;
    end
end
```

So you have to re-login after cookie.expires (timestamp) has been reached. To get the ImageBlock you can use multiple times (til `expires` >= now):

```ruby
response = httpClient.get("https://gallery.myserver.domain/main.php?g2_view=imageblock.External&g2_blocks=randomImage&g2_show=date&g2_maxSize=3000", :follow_redirect => true)

if not (isSuccess(response.status) || isRedirect(response.status))
   raise "Gallery2 at returns HTTP status code " + res.status.to_s() + " during fetch of image block."
end
```

`response` should contain a HTML page with a link to the random image. It is possible to parse the content and use XPath to extract the `<img>` tag and the `src` attribute (in Ruby with "Nokogiri"). So I can fetch the image with a further GET request directly. HTTPClient handles the cookies automatically (sends the cookie with the SID also for the last GET).

```ruby
def extractImageUri(content)
   fragment = Nokogiri::HTML(content)
   images = fragment.xpath("//img[@class='ImageFrame_image']")
   if (images.length != 1)
      raise "Cannot find the gallery image within: \n" + fragment
   end
   images[0]['src']
end

response = httpClient.get(extractImageUri(response.content))
if not (isSuccess(response.status) || isRedirect(response.status))
   raise "Gallery2 at returns HTTP status code " + res.status.to_s() + " during fetch of new image."
end

# store image from response.body
```

Thanks for your research
André

**Comment by gregstoll** [comment]
Awesome, glad you were able to figure it out!
