### ISSUE TITLE
Typo in commit 5ff2b4f9bcd7e448784136e7f8917a70b5bd2eb5 

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#75]
A typo in commit 5ff2b4f9bcd7e448784136e7f8917a70b5bd2eb5 causes huge amounts of 'PHP Warning:  Undefined array key 1 in /usr/local/www/gallery2/modules/core/classes/Gallery.class on line 910' log entries in the httpd error log. Fixed by the attached patch.

[gmdate-typo.txt](https://github.com/gregstoll/gallery2/files/9895758/gmdate-typo.txt)

**Comment by gregstoll** [comment]
Whoops, sorry, fixed in https://github.com/gregstoll/gallery2/commit/6013d28216ed89f6de2ce155fe4237eaba73e9e2 - thanks!
