### ISSUE TITLE
Module Rewrite is broken with PHP 8.0

### ISSUE THREAD

**Issue by Filou83** [gregstoll/gallery2#77]
Module Rewrite is broken with PHP 8.0

Can be fixed by editing "gallery2/modules/rewrite/AdminRewrite.inc"
Changing code from:
`function handleRequest(&$form)`
to:
`function handleRequest($form)`

P.S.: I love your work! Thank you very much!

**Comment by kaeni1Ohkohd** [comment]
The patch for issue #76 contains an identical fix for this

**Comment by gregstoll** [comment]
Thanks for the kind words and for the fix! The fix for #76 is in so this should be fixed now.
