### ISSUE TITLE
Default time format %X is crashing Site Administration

### ISSUE THREAD

**Issue by Filou83** [gregstoll/gallery2#79]
I used the default time format %X in site administration and with this it is crashing the main configuration.

I had to add a line of code in "gallery2/modules/core/classes/helpers/php-8.1-strftime-modified.class"

before
`//'%X' => $intl_formatter, // Preferred time representation based on locale, without the date`
I added
`'%X' => 'H:i:s',`

So I could access the main settings again.

**Comment by gregstoll** [comment]
Ah, thanks! I forgot those can be explicitly specified.
