### ISSUE TITLE
fix postgresql driver

### ISSUE THREAD

**Issue by matthewluckie** [gregstoll/gallery2#8]
the attached patches do the same thing that the changes to the mysql driver did.  I imagine the other database drivers have the same problems.

[patch-lib-adodb-driver-adodb-postgres64.inc.php.txt](https://github.com/gregstoll/gallery2/files/3195938/patch-lib-adodb-driver-adodb-postgres64.inc.php.txt)
[patch-modules-core-classes-GalleryStorage-PostgreSqlStorage.class.txt](https://github.com/gregstoll/gallery2/files/3195939/patch-modules-core-classes-GalleryStorage-PostgreSqlStorage.class.txt)

**Comment by gregstoll** [comment]
Sorry for the delay, I'm hoping to look at this this week. Thanks!

**Comment by gregstoll** [comment]
Applied these fixes in commit [5aa23dd](https://github.com/gregstoll/gallery2/commit/5aa23ddcbf1bfeeea2843d3ab957258bea5a2dff) and [dbade2c](https://github.com/gregstoll/gallery2/commit/dbade2ca15a2563343adc741277730eca7442a83).  Thanks so much!
