### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError when running Maintenance->Check short style URLs for filesystem conflicts

### ISSUE THREAD

**Issue by kaeni1Ohkohd** [gregstoll/gallery2#80]
Running 'Check short style URLs for filesystem conflicts' in Site Admin -> Maintenance gives the error 'PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /usr/local/www/gallery2/modules/core/classes/GalleryUtilities.class:495'. Fixed by the attached patch.

[checkshorturl.txt](https://github.com/gregstoll/gallery2/files/9896490/checkshorturl.txt)

**Comment by gregstoll** [comment]
Thanks as always :-)
