### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by Turk1701** [gregstoll/gallery2#92]
I'm trying to upgrade an old install from 2016 to this. 

I'm getting these errors on step 4:
`Fatal error: Uncaught Error: Call to undefined function each() in /home/turk1701/hotelblues.com/gallery2/upgrade/index.php:215 Stack trace: #0 /home/turk1701/hotelblues.com/gallery2/upgrade/steps/UpgradeCoreModuleStep.class(79): selectAdminUser(true) #1 /home/turk1701/hotelblues.com/gallery2/upgrade/index.php(180): UpgradeCoreModuleStep->processRequest() #2 {main} thrown in /home/turk1701/hotelblues.com/gallery2/upgrade/index.php on line 215`

**Comment by gregstoll** [comment]
Thanks for the report! I believe the linked PR will fix this.
