### ISSUE TITLE
Can't Delete Images

### ISSUE THREAD

**Issue by Turk1701** [gregstoll/gallery2#97]
Haha me again. Trying to delete images just results in a white page loading. When you view the page source there is nothing.

**Comment by gregstoll** [comment]
Hmm, I'm pretty sure I've seen this work before. A blank page might mean a PHP error - is there anything in your Apache (or whatever web server you're using) log?

**Comment by Turk1701** [comment]
Here is the error log.
`[Sat Dec 03 19:29:46.196013 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Non-static method RssMapHelper::fetchFeedsForItem() cannot be called statically in /home/turk1701/hotelblues.com/gallery2/modules/rss/module.inc:175, referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196162 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: Stack trace:, referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196182 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #0 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/helpers/GalleryEventHelper_simple.class(59): RssModule->handleEvent(Object(GalleryEvent)), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196197 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #1 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/GalleryCoreApi.class(2238): GalleryEventHelper_simple::postEvent(Object(GalleryEvent)), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196212 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #2 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/GalleryEntity.class(365): GalleryCoreApi::postEvent(Object(GalleryEvent)), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196227 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #3 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/GalleryFileSystemEntity.class(264): GalleryEntity->delete(), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196256 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #4 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/GalleryItem.class(329): GalleryFileSystemEntity->delete(), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196271 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #5 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/GalleryDataItem.class(236): GalleryItem->delete(), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196286 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #6 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/helpers/GalleryEntityHelper_medium.class(115): GalleryDataItem->delete(), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196301 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #7 /home/turk1701/hotelblues.com/gallery2/modules/core/classes/GalleryCoreApi.class(2377): GalleryEntityHelper_medium::deleteEntityById(43818, 'GalleryItem'), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196321 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #8 /home/turk1701/hotelblues.com/gallery2/modules/core/ItemDelete.inc(83): GalleryCoreApi::deleteEntityById(43818, 'GalleryItem'), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196337 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #9 /home/turk1701/hotelblues.com/gallery2/main.php(250): ItemDeleteController->handleRequest(Array), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196351 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #10 /home/turk1701/hotelblues.com/gallery2/main.php(104): _GalleryMain(false), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196365 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #11 /home/turk1701/hotelblues.com/gallery2/main.php(88): GalleryMain(), referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196379 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr: #12 {main}, referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818
[Sat Dec 03 19:29:46.196393 2022] [fcgid:warn] [pid 285966:tid 3887988418304] [client 68.187.77.160:53830] mod_fcgid: stderr:   thrown in /home/turk1701/hotelblues.com/gallery2/modules/rss/module.inc on line 175, referer: https://www.hotelblues.com/gallery2/main.php?g2_view=core.ItemAdmin&g2_subView=core.ItemDelete&g2_itemId=7773&g2_selectedId=43818`

**Comment by gregstoll** [comment]
OK, I just pushed [commit fe8893e7](https://github.com/gregstoll/gallery2/commit/fe8893e755aceca4aa96113f37a8c989b2501afa) which should fix at least part of this - let me know how it works!

**Comment by Turk1701** [comment]
That did it! Any chance you can fix that geturls plugin?

**Comment by gregstoll** [comment]
Great!

I can give it a shot but not tonight 🙂 Will try to get to it in the next few days.

**Comment by Turk1701** [comment]
> Great!
> 
> I can give it a shot but not tonight 🙂 Will try to get to it in the next few days.

Thank! No hurry or pressure.
